name: 3_wise_bears
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - langgraph
      - langchain
      - langchain-community
      - langchain-openai
      - jinja2
      - flask
